FROM nvidia/cuda:12.9.1-cudnn-runtime-ubuntu22.04

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends \
    software-properties-common \
    git \
    wget \
    curl \
    libglib2.0-0 \
    libsm6 \
    libxrender1 \
    libxext6 \
    libgl1 \
    && add-apt-repository ppa:deadsnakes/ppa \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
    python3.11 \
    python3.11-distutils \
    python3.11-venv \
    python3.11-dev \
    && rm -rf /var/lib/apt/lists/*


WORKDIR /app

RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.11 1

RUN apt-get update && apt-get remove -y python3-blinker

RUN python3 -m ensurepip --upgrade

COPY requirements.txt .

RUN python3 -m pip install --no-cache-dir -r requirements.txt

COPY . .

ENTRYPOINT ["python3", "./scripts/run_first_task_foundation.py", "--dataset_root", "./data/instereo2k_sample/", "--out_root", "./results/first_task", "--ckpt_dir", "./models/FoundationStereo/foundation_stereo_23-51-11.onnx", "--norm", "imagenet"]
